# Generated by Django 6.0.2 on 2026-02-20 07:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PilotApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_name', models.CharField(max_length=255)),
                ('industry', models.CharField(choices=[('Fintech', 'Fintech'), ('Manufacturing', 'Manufacturing'), ('Healthcare', 'Healthcare'), ('NGO', 'NGO'), ('Government Agency', 'Government Agency'), ('Religious Organization', 'Religious Organization'), ('Other', 'Other')], max_length=50)),
                ('organizational_scope', models.CharField(choices=[('Single Location', 'Single Location'), ('Multi-Region', 'Multi-Region'), ('Multi-Country', 'Multi-Country'), ('National-Level', 'National-Level')], max_length=50)),
                ('team_size', models.CharField(choices=[('1-20', '1-20'), ('21-100', '21-100'), ('101-500', '101-500'), ('500+', '500+')], max_length=20)),
                ('primary_challenge', models.CharField(choices=[('Fragmented Reporting', 'Fragmented Reporting'), ('KPI Visibility Gaps', 'KPI Visibility Gaps'), ('Risk & Compliance Oversight', 'Risk & Compliance Oversight'), ('Slow Decision Cycles', 'Slow Decision Cycles'), ('Operational Complexity', 'Operational Complexity'), ('Other', 'Other')], max_length=50)),
                ('challenge_description', models.TextField(blank=True)),
                ('sponsor_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('qualification_score', models.IntegerField(default=0)),
                ('priority_tier', models.CharField(choices=[('hot', '🔥 Hot (Immediate)'), ('warm', '🔆 Warm (Same Day)'), ('cool', '❄️ Cool (Next Day)'), ('nurture', '🌱 Nurture (Automated)')], default='nurture', max_length=10)),
                ('sample_report', models.FileField(blank=True, null=True, upload_to='pilot_reports/%Y/%m/')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('reviewed', 'Reviewed'), ('call_scheduled', 'Call Scheduled'), ('call_completed', 'Call Completed'), ('pilot_active', 'Pilot Active'), ('converted', 'Converted'), ('rejected', 'Rejected'), ('nurture', 'Nurture')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('alignment_call_scheduled', models.DateTimeField(blank=True, null=True)),
                ('pilot_start_date', models.DateField(blank=True, null=True)),
                ('utm_source', models.CharField(blank=True, max_length=100)),
                ('utm_campaign', models.CharField(blank=True, max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('internal_notes', models.TextField(blank=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pilot Application',
                'verbose_name_plural': 'Pilot Applications',
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['priority_tier', '-submitted_at'], name='leads_pilot_priorit_c665bf_idx'), models.Index(fields=['status', '-submitted_at'], name='leads_pilot_status_2d0c6d_idx'), models.Index(fields=['email'], name='leads_pilot_email_0ea310_idx')],
            },
        ),
    ]
