# Generated by Django 5.2.11 on 2026-02-20 14:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('seniority_level', models.CharField(choices=[('c_suite', 'C-Suite (CEO, CFO, COO, MD)'), ('vp_director', 'VP / Director'), ('senior_manager', 'Senior Manager'), ('manager', 'Manager'), ('other', 'Other')], max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('email_verified', models.CharField(choices=[('unverified', 'Unverified'), ('verified', 'Verified'), ('bounced', 'Bounced')], default='unverified', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('linkedin_url', models.URLField(blank=True)),
                ('is_primary_contact', models.BooleanField(default=False)),
                ('is_decision_maker', models.BooleanField(default=False)),
                ('emails_sent', models.IntegerField(default=0)),
                ('last_contacted_at', models.DateTimeField(blank=True, null=True)),
                ('do_not_contact', models.BooleanField(default=False)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['prospect', 'seniority_level', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='Prospect',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_name', models.CharField(max_length=255)),
                ('industry', models.CharField(max_length=100)),
                ('country', models.CharField(default='Uganda', max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('website', models.URLField(blank=True)),
                ('company_size', models.CharField(choices=[('micro', '1-20'), ('small', '21-100'), ('medium', '101-500'), ('large', '500+')], max_length=20)),
                ('complexity_score', models.IntegerField(default=0, help_text='1-10 scale')),
                ('multi_region', models.BooleanField(default=False)),
                ('reporting_intensity', models.IntegerField(default=0, help_text='1-10 scale')),
                ('archetype', models.CharField(choices=[('distributed_ops', 'Distributed Operations'), ('growth_efficiency', 'Growth & Capital Efficiency'), ('public_sector', 'Public Sector Oversight')], max_length=20)),
                ('decision_authority', models.CharField(choices=[('c_suite', 'C-Suite'), ('vp', 'VP/Director'), ('manager', 'Manager'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('status', models.CharField(choices=[('new', 'New'), ('researching', 'Researching'), ('qualified', 'Qualified'), ('contacted', 'Contacted'), ('engaged', 'Engaged'), ('opportunity', 'Opportunity'), ('rejected', 'Rejected'), ('unsubscribed', 'Unsubscribed')], default='new', max_length=20)),
                ('source', models.CharField(help_text='e.g., LinkedIn, URSB, Ministry Directory', max_length=100)),
                ('source_url', models.URLField(blank=True)),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Prospect',
                'verbose_name_plural': 'Prospects',
                'ordering': ['-complexity_score', 'organization_name'],
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('warming', 'Domain Warm-up'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('target_archetypes', models.JSONField(default=list, help_text='List of archetype codes')),
                ('target_countries', models.JSONField(default=list)),
                ('max_emails_per_week', models.IntegerField(default=50)),
                ('current_week_volume', models.IntegerField(default=0)),
                ('week_reset_at', models.DateTimeField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('warmup_week', models.IntegerField(default=0, help_text='Current warm-up week (0 = not started)')),
                ('warmup_started_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OutreachEmail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=300)),
                ('body', models.TextField()),
                ('body_rendered', models.TextField(help_text='Final rendered HTML')),
                ('scheduled_at', models.DateTimeField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('message_id', models.CharField(blank=True, help_text='AWS SES Message ID', max_length=200)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sending', 'Sending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('bounced', 'Bounced'), ('complained', 'Complained'), ('replied', 'Replied'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
                ('reply_body', models.TextField(blank=True)),
                ('engagement_stage', models.IntegerField(choices=[(1, 'Cold Outreach'), (2, 'Curious Response'), (3, 'Qualified Interest'), (4, 'Alignment Call Scheduled'), (5, 'Pilot Discussion'), (6, 'Proposal Phase')], default=1)),
                ('escalated_to_human', models.BooleanField(default=False)),
                ('escalated_at', models.DateTimeField(blank=True, null=True)),
                ('escalation_reason', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_emails', to=settings.AUTH_USER_MODEL)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outreach_emails', to='outreach.contact')),
                ('prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outreach_emails', to='outreach.prospect')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Engagement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('engagement_type', models.CharField(choices=[('reply', 'Reply'), ('bounce', 'Bounce'), ('complaint', 'Complaint'), ('open', 'Open'), ('click', 'Click'), ('forward', 'Forward')], max_length=20)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('raw_content', models.TextField(blank=True)),
                ('processed_content', models.TextField(blank=True)),
                ('sentiment', models.CharField(choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('objection_category', models.CharField(choices=[('none', 'None'), ('already_have_dashboards', 'Already Have Dashboards'), ('internal_reporting', 'Internal Reporting'), ('send_more_info', 'Send More Information'), ('no_budget', 'No Budget'), ('not_interested', 'Not Interested'), ('timing', 'Bad Timing'), ('other', 'Other')], default='none', max_length=30)),
                ('requires_response', models.BooleanField(default=False)),
                ('escalated', models.BooleanField(default=False)),
                ('human_reviewed', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('human_assigned', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('outreach_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagements', to='outreach.outreachemail')),
            ],
            options={
                'ordering': ['-captured_at'],
            },
        ),
        migrations.AddField(
            model_name='contact',
            name='prospect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='outreach.prospect'),
        ),
        migrations.CreateModel(
            name='SequenceStage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage_number', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('subject_template', models.CharField(max_length=300)),
                ('body_template', models.TextField(help_text='Use {{first_name}}, {{organization}}, {{title}} variables')),
                ('delay_days', models.IntegerField(default=0, help_text='Days after previous stage')),
                ('send_time_window_start', models.TimeField(default='09:00')),
                ('send_time_window_end', models.TimeField(default='11:00')),
                ('require_reply_to_advance', models.BooleanField(default=False, help_text='If true, sequence pauses until reply')),
                ('auto_advance_on_no_reply', models.BooleanField(default=True, help_text='Auto-advance if no reply after delay_days')),
                ('include_unsubscribe', models.BooleanField(default=True)),
                ('track_opens', models.BooleanField(default=True)),
                ('track_clicks', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='outreach.campaign')),
            ],
            options={
                'ordering': ['campaign', 'stage_number'],
                'unique_together': {('campaign', 'stage_number')},
            },
        ),
        migrations.AddField(
            model_name='outreachemail',
            name='sequence_stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='outreach.sequencestage'),
        ),
        migrations.CreateModel(
            name='SuppressionList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('domain', models.CharField(blank=True, max_length=255)),
                ('reason', models.CharField(choices=[('unsubscribe', 'Unsubscribe Request'), ('bounce', 'Hard Bounce'), ('complaint', 'Spam Complaint'), ('manual', 'Manual Add')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='outreach.campaign')),
            ],
            options={
                'verbose_name': 'Suppression List Entry',
                'verbose_name_plural': 'Suppression List',
            },
        ),
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together={('prospect', 'email')},
        ),
    ]
