# Generated by Django 6.0.2 on 2026-02-20 07:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlignmentCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_at', models.DateTimeField()),
                ('duration_minutes', models.IntegerField(default=30)),
                ('meeting_link', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('outcome', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('no_show', 'No Show'), ('rescheduled', 'Rescheduled'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hosted_calls', to=settings.AUTH_USER_MODEL)),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alignment_call', to='leads.pilotapplication')),
            ],
            options={
                'verbose_name': 'Alignment Call',
                'verbose_name_plural': 'Alignment Calls',
                'ordering': ['scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='PilotEngagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('weekly_briefs_delivered', models.IntegerField(default=0)),
                ('kpis_configured', models.JSONField(blank=True, default=list)),
                ('stakeholder_count', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('onboarding', 'Onboarding'), ('active', 'Active'), ('review', '30-Day Review'), ('extended', 'Extended'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='onboarding', max_length=20)),
                ('conversion_status', models.CharField(choices=[('in_progress', 'In Progress'), ('converted', 'Converted to Paid'), ('churned', 'Churned'), ('nurture', 'Moved to Nurture')], default='in_progress', max_length=20)),
                ('monthly_recurring_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pilot_engagement', to='leads.pilotapplication')),
            ],
            options={
                'verbose_name': 'Pilot Engagement',
                'verbose_name_plural': 'Pilot Engagements',
                'ordering': ['-start_date'],
            },
        ),
    ]
